#if !canImport(ObjectiveC)
import XCTest

extension AccumulatePerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccumulatePerformanceTests = [
        ("testAccumulatingProductLinear", testAccumulatingProductLinear),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccumulatePerformanceTests.__allTests__AccumulatePerformanceTests),
    ]
}
#endif
