#if !canImport(ObjectiveC)
import XCTest

extension CombinatoricsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CombinatoricsTests = [
        ("testCartesianProductOfTwoArrays", testCartesianProductOfTwoArrays),
        ("testPermutations", testPermutations),
        ("testPermutationsEmpty", testPermutationsEmpty),
    ]
}

extension OrderedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderedTests = [
        ("testOrderedEqual", testOrderedEqual),
        ("testOrderInOrder", testOrderInOrder),
        ("testOrderNeedsOrdering", testOrderNeedsOrdering),
    ]
}

extension RotateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RotateTests = [
        ("testRotateBy0", testRotateBy0),
        ("testRotateBy1", testRotateBy1),
        ("testRotateByGreaterThanCount", testRotateByGreaterThanCount),
        ("testRotateByNegative1", testRotateByNegative1),
    ]
}

extension SplitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SplitTests = [
        ("testSplitAndExtractEmpty", testSplitAndExtractEmpty),
        ("testSplitAndExtractMutlple", testSplitAndExtractMutlple),
        ("testSplitAndExtractSingle", testSplitAndExtractSingle),
    ]
}

extension StableSortTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StableSortTests = [
        ("testStableSort", testStableSort),
    ]
}

extension SwapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwapTests = [
        ("testImmutableSwapped", testImmutableSwapped),
        ("testImmutableSwappedWithPredicateFalse", testImmutableSwappedWithPredicateFalse),
        ("testImmutableSwappedWithPredicateTrue", testImmutableSwappedWithPredicateTrue),
        ("testInoutSwapWithPredicateFalse", testInoutSwapWithPredicateFalse),
        ("testInoutSwapWithPredicateTrue", testInoutSwapWithPredicateTrue),
    ]
}

extension TupleMapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TupleMapTests = [
        ("testMapAB", testMapAB),
        ("testMapABC", testMapABC),
        ("testMapTupleAB", testMapTupleAB),
        ("testMapTupleABC", testMapTupleABC),
    ]
}

extension UnzipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnzipTests = [
        ("testNonEmpty", testNonEmpty),
        ("testPerformance", testPerformance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CombinatoricsTests.__allTests__CombinatoricsTests),
        testCase(OrderedTests.__allTests__OrderedTests),
        testCase(RotateTests.__allTests__RotateTests),
        testCase(SplitTests.__allTests__SplitTests),
        testCase(StableSortTests.__allTests__StableSortTests),
        testCase(SwapTests.__allTests__SwapTests),
        testCase(TupleMapTests.__allTests__TupleMapTests),
        testCase(UnzipTests.__allTests__UnzipTests),
    ]
}
#endif
