#if !canImport(ObjectiveC)
import XCTest

extension AccumulateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccumulateTests = [
        ("testAccumulatingProduct", testAccumulatingProduct),
        ("testFloatArrayAccumulatingSum", testFloatArrayAccumulatingSum),
        ("testIntArrayAccumulatingSum", testIntArrayAccumulatingSum),
    ]
}

extension SequenceAlgebraTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SequenceAlgebraTests = [
        ("testSetIntersections", testSetIntersections),
        ("testSumOfAdditiveSemigroup", testSumOfAdditiveSemigroup),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccumulateTests.__allTests__AccumulateTests),
        testCase(SequenceAlgebraTests.__allTests__SequenceAlgebraTests),
    ]
}
#endif
