#if !canImport(ObjectiveC)
import XCTest

extension DestructureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DestructureTests = [
        ("testArrayDestructured", testArrayDestructured),
        ("testArrayDestructuredNil", testArrayDestructuredNil),
        ("testArraySliceDestructured", testArraySliceDestructured),
        ("testArraySliceDestructuredNil", testArraySliceDestructuredNil),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DestructureTests.__allTests__DestructureTests),
    ]
}
#endif
