#if !canImport(ObjectiveC)
import XCTest

extension AVLTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AVLTreeTests = [
        ("testInitSequence", testInitSequence),
        ("testManyValuesDecreasing", testManyValuesDecreasing),
        ("testManyValuesIncreasing", testManyValuesIncreasing),
        ("testManyValuesRandom", testManyValuesRandom),
        ("testSingleNodeHeight", testSingleNodeHeight),
        ("testThreeNodes", testThreeNodes),
        ("testTwoNodes", testTwoNodes),
    ]
}

extension AdjacencyListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AdjacencyListTests = [
        ("testDAGifySimpleCycle", testDAGifySimpleCycle),
        ("testDAGifySimpleCycleDisjoint", testDAGifySimpleCycleDisjoint),
        ("testDAGifySimpleCycleThreeNodesMixed", testDAGifySimpleCycleThreeNodesMixed),
        ("testDAGifySimpleCycleTwoNodes", testDAGifySimpleCycleTwoNodes),
        ("testDAGifySimpleNoCycleDisjoint", testDAGifySimpleNoCycleDisjoint),
        ("testDAGifySimpleNonCycle", testDAGifySimpleNonCycle),
        ("testSafeInitializer", testSafeInitializer),
        ("testSimpleCycle", testSimpleCycle),
        ("testSimpleCycleDisjoint", testSimpleCycleDisjoint),
        ("testSimpleCycleThreeNodesMixed", testSimpleCycleThreeNodesMixed),
        ("testSimpleCycleTwoNodes", testSimpleCycleTwoNodes),
        ("testSimpleNoCycleDisjoint", testSimpleNoCycleDisjoint),
        ("testSimpleNonCycle", testSimpleNonCycle),
    ]
}

extension ArrayExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayExtensionsTests = [
        ("testInsertingAtIndexAtBeginning", testInsertingAtIndexAtBeginning),
        ("testInsertingAtIndexAtEnd", testInsertingAtIndexAtEnd),
        ("testInsertingAtIndexInMiddle", testInsertingAtIndexInMiddle),
        ("testLastAmountEmpty", testLastAmountEmpty),
        ("testLastAmountEquiv", testLastAmountEquiv),
        ("testLastAmountTooMany", testLastAmountTooMany),
        ("testLastAmountValid", testLastAmountValid),
        ("testPenultimateNil", testPenultimateNil),
        ("testPenultimateValid", testPenultimateValid),
        ("testReplaceElementAtIndex", testReplaceElementAtIndex),
        ("testReplaceFirst", testReplaceFirst),
        ("testReplaceLast", testReplaceLast),
        ("testSafeSubscriptNil", testSafeSubscriptNil),
        ("testSafeSubscriptValid", testSafeSubscriptValid),
        ("testSecondNil", testSecondNil),
        ("testSecondVaild", testSecondVaild),
    ]
}

extension BimapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BimapTests = [
        ("testCompose", testCompose),
        ("testComposeOperator", testComposeOperator),
        ("testInitEmpty", testInitEmpty),
        ("testKeySubscript", testKeySubscript),
        ("testRemoveAll", testRemoveAll),
        ("testRemoveKey", testRemoveKey),
        ("testRemoveValue", testRemoveValue),
        ("testUpdateKey", testUpdateKey),
        ("testUpdateValue", testUpdateValue),
        ("testValueSubscript", testValueSubscript),
    ]
}

extension BinaryHeapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryHeapTests = [
        ("testBalance", testBalance),
        ("testBasicInsertPop", testBasicInsertPop),
        ("testPopNil", testPopNil),
        ("testSimpleBalance", testSimpleBalance),
    ]
}

extension BinarySearchTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinarySearchTreeTests = [
        ("testInitSequence", testInitSequence),
    ]
}

extension CircularArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CircularArrayTests = [
        ("testCollection", testCollection),
        ("testElementAtTheEnd", testElementAtTheEnd),
        ("testElementAtZero", testElementAtZero),
        ("testElementInTheMiddle", testElementInTheMiddle),
        ("testElementOutOfNormalBounds", testElementOutOfNormalBounds),
        ("testEquatable", testEquatable),
        ("testRangeAfterUpToOutOfOrderOverflow", testRangeAfterUpToOutOfOrderOverflow),
        ("testRangeInOrderOverflow", testRangeInOrderOverflow),
        ("testRangeInOrderWithinBounds", testRangeInOrderWithinBounds),
        ("testRangeOutOfOrderOverflow", testRangeOutOfOrderOverflow),
        ("testReversed", testReversed),
        ("testSequence", testSequence),
    ]
}

extension ContiguousSegmentCollectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContiguousSegmentCollectionTests = [
        ("testCollectionFragmentSequence", testCollectionFragmentSequence),
        ("testContains", testContains),
        ("testFragmentA", testFragmentA),
        ("testFragmentB", testFragmentB),
        ("testFragmentC", testFragmentC),
        ("testFragmentD", testFragmentD),
        ("testFragmentE", testFragmentE),
        ("testFragmentF", testFragmentF),
        ("testFragmentG", testFragmentG),
        ("testFragmentH", testFragmentH),
        ("testFragmentI", testFragmentI),
        ("testFragmentOfFragmentBodyBody", testFragmentOfFragmentBodyBody),
        ("testFragmentOfFragmentBodyTail", testFragmentOfFragmentBodyTail),
        ("testFragmentOfFragmentHeadBody", testFragmentOfFragmentHeadBody),
        ("testFragmentOfFragmentHeadHead", testFragmentOfFragmentHeadHead),
        ("testFragmentOfFragmentTailTail", testFragmentOfFragmentTailTail),
        ("testInitSegments", testInitSegments),
        ("testLength", testLength),
        ("testOffsets", testOffsets),
        ("testRandomAccess", testRandomAccess),
        ("testSegments", testSegments),
    ]
}

extension CrossTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CrossTests = [
        ("testComparableFalseEqual", testComparableFalseEqual),
        ("testComparableLexicographic", testComparableLexicographic),
        ("testComparableLexicographicFalse", testComparableLexicographicFalse),
        ("testDescription", testDescription),
        ("testMap", testMap),
    ]
}

extension DictionaryProtocolsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DictionaryProtocolsTests = [
        ("testDictionaryInitWithArrayOfTuples", testDictionaryInitWithArrayOfTuples),
        ("testDictionaryInitWithArrays", testDictionaryInitWithArrays),
        ("testEnsureDictionaryTypeValueNotYetExtant", testEnsureDictionaryTypeValueNotYetExtant),
        ("testEnsureDictionaryTypeValuePreexisting", testEnsureDictionaryTypeValuePreexisting),
        ("testEnsureRangeReplaceableCollectionValueForKeyNotYetExtant", testEnsureRangeReplaceableCollectionValueForKeyNotYetExtant),
        ("testEnsureRangeReplaceableCollectionValueForKeyPreexisting", testEnsureRangeReplaceableCollectionValueForKeyPreexisting),
        ("testEnsureSetAlgebraValueForKeyNotYetExtant", testEnsureSetAlgebraValueForKeyNotYetExtant),
        ("testEnsureSetAlgebraValueForKeyPreexisting", testEnsureSetAlgebraValueForKeyPreexisting),
        ("testEqualitySimple", testEqualitySimple),
        ("testMergedNestedDict", testMergedNestedDict),
        ("testMergedNewDictOvercomesOriginal", testMergedNewDictOvercomesOriginal),
        ("testMergeNestedDict", testMergeNestedDict),
        ("testMergeNewDictOvercomesOriginal", testMergeNewDictOvercomesOriginal),
        ("testSafelyAndUniquelyAppendValueNotExtant", testSafelyAndUniquelyAppendValueNotExtant),
        ("testSafelyAndUniquelyAppendValuePreexisting", testSafelyAndUniquelyAppendValuePreexisting),
        ("testSafelyAppendContentsToExisting", testSafelyAppendContentsToExisting),
        ("testSafelyAppendContentsToNotYetExtant", testSafelyAppendContentsToNotYetExtant),
        ("testSafelyAppendToExisting", testSafelyAppendToExisting),
        ("testSafelyAppendToNotYetExisting", testSafelyAppendToNotYetExisting),
        ("testSafelyFormUnionExisting", testSafelyFormUnionExisting),
        ("testSafelyFormUnionNotYetExtant", testSafelyFormUnionNotYetExtant),
        ("testSafelyInsertToExisting", testSafelyInsertToExisting),
        ("testSafelyInsertToNotYetExisting", testSafelyInsertToNotYetExisting),
    ]
}

extension DirectedGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DirectedGraphTests = [
        ("testDirectedGraphInsertNodes", testDirectedGraphInsertNodes),
        ("testEdgesFromNode", testEdgesFromNode),
        ("testShortestPathThreeNodes", testShortestPathThreeNodes),
        ("testShortestUnweightedPathSingleNode", testShortestUnweightedPathSingleNode),
        ("testShortestUnweightedPathTwoDirectionallyConnectedNodes", testShortestUnweightedPathTwoDirectionallyConnectedNodes),
        ("testShortestUnweightedPathTwoUnconnectedNodes", testShortestUnweightedPathTwoUnconnectedNodes),
    ]
}

extension EitherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EitherTests = [
        ("testEquatable", testEquatable),
    ]
}

extension GraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphTests = [
        ("testBreadthFirstSearch", testBreadthFirstSearch),
        ("testEdgesCount", testEdgesCount),
        ("testInsertNodes", testInsertNodes),
        ("testNeighbors", testNeighbors),
        ("testNeighborsInSet", testNeighborsInSet),
        ("testNodesCount", testNodesCount),
        ("testRemoveEdge", testRemoveEdge),
    ]
}

extension HomogeneityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HomogeneityTests = [
        ("testIsHeterogeneousFalse", testIsHeterogeneousFalse),
        ("testIsHomoegeneous", testIsHomoegeneous),
        ("testIsHomogeneousFail", testIsHomogeneousFail),
        ("testIsHomogenousEmptyTrue", testIsHomogenousEmptyTrue),
        ("testIsHomogenousSingleElementTrue", testIsHomogenousSingleElementTrue),
    ]
}

extension IntervalRelationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntervalRelationTests = [
        ("testContains", testContains),
        ("testDuring", testDuring),
        ("testEquals", testEquals),
        ("testFinishedBy", testFinishedBy),
        ("testFinishes", testFinishes),
        ("testInverseOfContainedByIsContains", testInverseOfContainedByIsContains),
        ("testInverseOfEqualsIsEquals", testInverseOfEqualsIsEquals),
        ("testInverseOfPrecedesIsPrecededBy", testInverseOfPrecedesIsPrecededBy),
        ("testMeets", testMeets),
        ("testMetBy", testMetBy),
        ("testOverlappedBy", testOverlappedBy),
        ("testOverlaps", testOverlaps),
        ("testPrecededBy", testPrecededBy),
        ("testPrecedes", testPrecedes),
        ("testStartedBy", testStartedBy),
        ("testStarts", testStarts),
    ]
}

extension InvertibleEnumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InvertibleEnumTests = [
        ("testEventCountInverse", testEventCountInverse),
        ("testOddCountInverse", testOddCountInverse),
    ]
}

extension LinkedListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LinkedListTests = [
        ("testCollection", testCollection),
        ("testEquatable", testEquatable),
        ("testInitArray", testInitArray),
        ("testInitEmpty", testInitEmpty),
        ("testPop", testPop),
        ("testPopTail", testPopTail),
        ("testPush", testPush),
    ]
}

extension MatrixTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MatrixTests = [
        ("testEquivalenceFalse", testEquivalenceFalse),
        ("testEquivalenceTrue", testEquivalenceTrue),
        ("testInit", testInit),
        ("testPrint", testPrint),
        ("testRowAndColumnSubscriptsGetter", testRowAndColumnSubscriptsGetter),
        ("testRowAndColumnSubscriptsSetter", testRowAndColumnSubscriptsSetter),
        ("testRowsAndColumns", testRowsAndColumns),
        ("testSequence", testSequence),
        ("testSubscript", testSubscript),
    ]
}

extension MetatypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MetatypeTests = [
        ("testEquatable", testEquatable),
        ("testEquatableFalse", testEquatableFalse),
        ("testHashableEqual", testHashableEqual),
        ("testHashableNotEqual", testHashableNotEqual),
        ("testInit", testInit),
    ]
}

extension MutableGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MutableGraphTests = [
        ("testBidirectionalRelationshipIsTwoDirectedRelationships", testBidirectionalRelationshipIsTwoDirectedRelationships),
        ("testEdgeBetweenTwoVertices", testEdgeBetweenTwoVertices),
        ("testMultipleAttemptsToAddSameNode", testMultipleAttemptsToAddSameNode),
        ("testSingleVertex", testSingleVertex),
        ("testWeightFromSingleEdge", testWeightFromSingleEdge),
    ]
}

extension NewTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NewTypeTests = [
        ("testComparable", testComparable),
        ("testExpressibleByFloatLiteral", testExpressibleByFloatLiteral),
        ("testExpressibleByIntegerLiteral", testExpressibleByIntegerLiteral),
        ("testNumeric", testNumeric),
        ("testSignedNumeric", testSignedNumeric),
    ]
}

extension OrderedDictionaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderedDictionaryTests = [
        ("testAppend", testAppend),
        ("testAppendContentsOfEmptyDict", testAppendContentsOfEmptyDict),
        ("testAppendContentsOfEmptyToNonEmptyDict", testAppendContentsOfEmptyToNonEmptyDict),
        ("testAppendContentsOfNonEmptyToEmptyDict", testAppendContentsOfNonEmptyToEmptyDict),
        ("testEquatable", testEquatable),
        ("testInit", testInit),
        ("testInsert", testInsert),
        ("testIterationOrdered", testIterationOrdered),
        ("testSubscriptIntValid", testSubscriptIntValid),
        ("testSubscriptKeyNil", testSubscriptKeyNil),
        ("testSubscriptKeyValid", testSubscriptKeyValid),
    ]
}

extension OrderedPairTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderedPairTests = [
        ("testDescription", testDescription),
        ("testMap", testMap),
    ]
}

extension PairsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PairsTests = [
        ("testPairs", testPairs),
    ]
}

extension QueueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QueueTests = [
        ("testEnqueuedDequeue", testEnqueuedDequeue),
        ("testEnqueuedNotEmpty", testEnqueuedNotEmpty),
        ("testEnqueuedPeekNotNil", testEnqueuedPeekNotNil),
        ("testInitEmpty", testInitEmpty),
        ("testInitPeekNil", testInitPeekNil),
    ]
}

extension ReferenceTreeProtocolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReferenceTreeProtocolTests = [
        ("testAddChild", testAddChild),
        ("testAddChildrenArray", testAddChildrenArray),
        ("testAddChildrenVariadic", testAddChildrenVariadic),
        ("testAncestorAtDistanceGrandchild", testAncestorAtDistanceGrandchild),
        ("testAncestorAtDistanceOnlyChild", testAncestorAtDistanceOnlyChild),
        ("testAncestorAtDistanceSingleNil", testAncestorAtDistanceSingleNil),
        ("testAncestorAtDistanceSingleValid", testAncestorAtDistanceSingleValid),
        ("testChildAtIndexNil", testChildAtIndexNil),
        ("testChildAtIndexNilEmpty", testChildAtIndexNilEmpty),
        ("testChildAtIndexValidMultiple", testChildAtIndexValidMultiple),
        ("testChildAtIndexValidSingle", testChildAtIndexValidSingle),
        ("testDepthGrandchild_2", testDepthGrandchild_2),
        ("testDepthOnlyChild_1", testDepthOnlyChild_1),
        ("testDepthRoot_1", testDepthRoot_1),
        ("testHasAncestorGrandchild", testHasAncestorGrandchild),
        ("testHasAncestorOnlyChild", testHasAncestorOnlyChild),
        ("testHasAncestorSingleNode", testHasAncestorSingleNode),
        ("testHasChildFalse", testHasChildFalse),
        ("testHasChildFalseEmpty", testHasChildFalseEmpty),
        ("testHasChildTrue", testHasChildTrue),
        ("testHasDescendentFalseSingleNode", testHasDescendentFalseSingleNode),
        ("testHasDescendentGrandparent", testHasDescendentGrandparent),
        ("testHasDescendentParent", testHasDescendentParent),
        ("testHeightGrandparent_2", testHeightGrandparent_2),
        ("testHeightParent_1", testHeightParent_1),
        ("testHeightSingleNode_0", testHeightSingleNode_0),
        ("testInsertChildAtIndexThrows", testInsertChildAtIndexThrows),
        ("testInsertChildAtIndexValidEmpty", testInsertChildAtIndexValidEmpty),
        ("testInsertChildAtIndexValidNotEmpty", testInsertChildAtIndexValidNotEmpty),
        ("testIsContainerFalse", testIsContainerFalse),
        ("testIsContainerTrue", testIsContainerTrue),
        ("testIsLeafFalse", testIsLeafFalse),
        ("testIsLeafTrueLeaf", testIsLeafTrueLeaf),
        ("testIsLeafTrueRoot", testIsLeafTrueRoot),
        ("testIsRootTrueContainer", testIsRootTrueContainer),
        ("testIsRootTrueSingleNode", testIsRootTrueSingleNode),
        ("testLeafAtIndexNilLeaf", testLeafAtIndexNilLeaf),
        ("testLeafAtIndexNilMultipleDepth", testLeafAtIndexNilMultipleDepth),
        ("testLeafAtIndexNilNoLeaves", testLeafAtIndexNilNoLeaves),
        ("testLeafAtIndexNilSingleDepth", testLeafAtIndexNilSingleDepth),
        ("testLeafAtIndexSelf", testLeafAtIndexSelf),
        ("testLeafAtIndexValidMultipleDepth", testLeafAtIndexValidMultipleDepth),
        ("testLeafAtIndexValidSingleDepth", testLeafAtIndexValidSingleDepth),
        ("testPathToRootGrandchild", testPathToRootGrandchild),
        ("testPathToRootOnlyChild", testPathToRootOnlyChild),
        ("testPathToRootSingleNode", testPathToRootSingleNode),
        ("testRemoveChildAtIndexThrows", testRemoveChildAtIndexThrows),
        ("testRemoveChildAtIndexValid", testRemoveChildAtIndexValid),
        ("testRemoveChildThrows", testRemoveChildThrows),
        ("testRemoveChildValid", testRemoveChildValid),
        ("testRootGrandchild", testRootGrandchild),
        ("testRootOnlyChild", testRootOnlyChild),
        ("testRootSelfSingleNode", testRootSelfSingleNode),
        ("testUnbalancedGrandParent_2", testUnbalancedGrandParent_2),
    ]
}

extension ReferenceTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReferenceTreeTests = [
        ("testAddChild", testAddChild),
        ("testAddChildrenArray", testAddChildrenArray),
        ("testAddChildrenVariadic", testAddChildrenVariadic),
        ("testAncestorAtDistanceGrandchild", testAncestorAtDistanceGrandchild),
        ("testAncestorAtDistanceOnlyChild", testAncestorAtDistanceOnlyChild),
        ("testAncestorAtDistanceSingleNil", testAncestorAtDistanceSingleNil),
        ("testAncestorAtDistanceSingleValid", testAncestorAtDistanceSingleValid),
        ("testChildAtIndexNil", testChildAtIndexNil),
        ("testChildAtIndexNilEmpty", testChildAtIndexNilEmpty),
        ("testChildAtIndexValidMultiple", testChildAtIndexValidMultiple),
        ("testChildAtIndexValidSingle", testChildAtIndexValidSingle),
        ("testDepthGrandchild_2", testDepthGrandchild_2),
        ("testDepthOnlyChild_1", testDepthOnlyChild_1),
        ("testDepthRoot_1", testDepthRoot_1),
        ("testHasAncestorGrandchild", testHasAncestorGrandchild),
        ("testHasAncestorOnlyChild", testHasAncestorOnlyChild),
        ("testHasAncestorSingleNode", testHasAncestorSingleNode),
        ("testHasChildFalse", testHasChildFalse),
        ("testHasChildFalseEmpty", testHasChildFalseEmpty),
        ("testHasChildTrue", testHasChildTrue),
        ("testHasDescendentFalseSingleNode", testHasDescendentFalseSingleNode),
        ("testHasDescendentGrandparent", testHasDescendentGrandparent),
        ("testHasDescendentParent", testHasDescendentParent),
        ("testHeightGrandparent_2", testHeightGrandparent_2),
        ("testHeightParent_1", testHeightParent_1),
        ("testHeightSingleNode_0", testHeightSingleNode_0),
        ("testInsertChildAtIndexThrows", testInsertChildAtIndexThrows),
        ("testInsertChildAtIndexValidEmpty", testInsertChildAtIndexValidEmpty),
        ("testInsertChildAtIndexValidNotEmpty", testInsertChildAtIndexValidNotEmpty),
        ("testIsContainerFalse", testIsContainerFalse),
        ("testIsContainerTrue", testIsContainerTrue),
        ("testIsLeafFalse", testIsLeafFalse),
        ("testIsLeafTrueLeaf", testIsLeafTrueLeaf),
        ("testIsLeafTrueRoot", testIsLeafTrueRoot),
        ("testIsRootTrueContainer", testIsRootTrueContainer),
        ("testIsRootTrueSingleNode", testIsRootTrueSingleNode),
        ("testLeafAtIndexNilLeaf", testLeafAtIndexNilLeaf),
        ("testLeafAtIndexNilMultipleDepth", testLeafAtIndexNilMultipleDepth),
        ("testLeafAtIndexNilNoLeaves", testLeafAtIndexNilNoLeaves),
        ("testLeafAtIndexNilSingleDepth", testLeafAtIndexNilSingleDepth),
        ("testLeafAtIndexSelf", testLeafAtIndexSelf),
        ("testLeafAtIndexValidMultipleDepth", testLeafAtIndexValidMultipleDepth),
        ("testLeafAtIndexValidSingleDepth", testLeafAtIndexValidSingleDepth),
        ("testPathToRootGrandchild", testPathToRootGrandchild),
        ("testPathToRootOnlyChild", testPathToRootOnlyChild),
        ("testPathToRootSingleNode", testPathToRootSingleNode),
        ("testRemoveChildAtIndexThrows", testRemoveChildAtIndexThrows),
        ("testRemoveChildAtIndexValid", testRemoveChildAtIndexValid),
        ("testRemoveChildThrows", testRemoveChildThrows),
        ("testRemoveChildValid", testRemoveChildValid),
        ("testRootGrandchild", testRootGrandchild),
        ("testRootOnlyChild", testRootOnlyChild),
        ("testRootSelfSingleNode", testRootSelfSingleNode),
        ("testUnbalancedGrandParent_2", testUnbalancedGrandParent_2),
    ]
}

extension SortedArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SortedArrayTests = [
        ("testAdd", testAdd),
        ("testEndIndex", testEndIndex),
        ("testIndex", testIndex),
        ("testInitEmpty", testInitEmpty),
        ("testInitWithArraySorted", testInitWithArraySorted),
        ("testInitWithPresorted", testInitWithPresorted),
        ("testInsertAtBeginning", testInsertAtBeginning),
        ("testInsertAtEnd", testInsertAtEnd),
        ("testInsertElements", testInsertElements),
        ("testInsertInMiddle", testInsertInMiddle),
        ("testRemove", testRemove),
        ("testStartIndex", testStartIndex),
        ("testSubscript", testSubscript),
    ]
}

extension SortedDictionaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SortedDictionaryTests = [
        ("testGetSubscript", testGetSubscript),
        ("testInitPresorted", testInitPresorted),
        ("testInsert", testInsert),
        ("testInsertContentsOfSortedDictionary", testInsertContentsOfSortedDictionary),
        ("testIterationSorted", testIterationSorted),
        ("testRemoveViaSubscript", testRemoveViaSubscript),
        ("testSetSubscript", testSetSubscript),
        ("testSorted", testSorted),
        ("testSubscriptWithFloatKey", testSubscriptWithFloatKey),
        ("testValueItIndex", testValueItIndex),
    ]
}

extension StackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StackTests = [
        ("testDestructured", testDestructured),
        ("testEquatable", testEquatable),
        ("testInitStackWithArray", testInitStackWithArray),
        ("testPop", testPop),
        ("testPopAmountNotNil", testPopAmountNotNil),
        ("testPopTooManyNil", testPopTooManyNil),
        ("testPush", testPush),
        ("testTop", testTop),
    ]
}

extension SubsetsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubsetsTests = [
        ("testSubsetsCarinalityGreaterThanCountEmpty", testSubsetsCarinalityGreaterThanCountEmpty),
        ("testSubsetsDouble", testSubsetsDouble),
        ("testSubsetsEmptyEmpty", testSubsetsEmptyEmpty),
        ("testSubsetsQuadruple", testSubsetsQuadruple),
        ("testSubsetsTriple", testSubsetsTriple),
    ]
}

extension TreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TreeTests = [
        ("testHeightBranchSingleDepthOne", testHeightBranchSingleDepthOne),
        ("testHeightLeafZero", testHeightLeafZero),
        ("testHeightMany", testHeightMany),
        ("testHeightNested", testHeightNested),
        ("testInitWithSequence", testInitWithSequence),
        ("testInitWithValueAndEmptyArray", testInitWithValueAndEmptyArray),
        ("testInsertBranchAtBeginningSingleDepth", testInsertBranchAtBeginningSingleDepth),
        ("testInsertBranchAtEndSingleDepth", testInsertBranchAtEndSingleDepth),
        ("testInsertBranchInMiddleSingleDepth", testInsertBranchInMiddleSingleDepth),
        ("testInsertBranchReallyNested", testInsertBranchReallyNested),
        ("testInsertLeafAtBeginningSingleDepth", testInsertLeafAtBeginningSingleDepth),
        ("testInsertLeafNested", testInsertLeafNested),
        ("testInsertLeafNestedLessNested", testInsertLeafNestedLessNested),
        ("testLeafInit", testLeafInit),
        ("testLeavesBranchMultipleTrees", testLeavesBranchMultipleTrees),
        ("testLeavesBranchSingleChild", testLeavesBranchSingleChild),
        ("testLeavesLeaf", testLeavesLeaf),
        ("testLeavesMany", testLeavesMany),
        ("testLeavesMultipleDepth", testLeavesMultipleDepth),
        ("testMap", testMap),
        ("testPath", testPath),
        ("testPathLeaf", testPathLeaf),
        ("testReplaceAtPathNested", testReplaceAtPathNested),
        ("testReplaceLeafAtPath", testReplaceLeafAtPath),
        ("testReplacingLeafAtBegining", testReplacingLeafAtBegining),
        ("testReplacingLeafAtEnd", testReplacingLeafAtEnd),
        ("testReplacingLeafInMiddle", testReplacingLeafInMiddle),
        ("testTreeZip", testTreeZip),
        ("testUpdateValueBranch", testUpdateValueBranch),
        ("testUpdatingValueLeaf", testUpdatingValueLeaf),
        ("testZipLeaves", testZipLeaves),
        ("testZipLeavesWithTransform", testZipLeavesWithTransform),
    ]
}

extension UnorderedPairTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnorderedPairTests = [
        ("testDescription", testDescription),
        ("testEquatable", testEquatable),
        ("testHashValuesInt", testHashValuesInt),
        ("testHashValuesString", testHashValuesString),
        ("testManyHashValuesIntForCollisions", testManyHashValuesIntForCollisions),
        ("testManyHashValuesString", testManyHashValuesString),
        ("testManyHashValuesStringForCollisions", testManyHashValuesStringForCollisions),
        ("testMap", testMap),
    ]
}

extension WeightedDirectedGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WeightedDirectedGraphTests = [
        ("testEdgesFromNode", testEdgesFromNode),
        ("testShortestPathTwoOptions", testShortestPathTwoOptions),
        ("testWeightedDirectedGraphInsertNodes", testWeightedDirectedGraphInsertNodes),
    ]
}

extension WeightedGraphTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WeightedGraphTests = [
        ("testContains", testContains),
        ("testInsertNodes", testInsertNodes),
        ("testNeighbors", testNeighbors),
        ("testRemoveEdge", testRemoveEdge),
        ("testUnweightedFromDirected", testUnweightedFromDirected),
        ("testUnweightedFromUndirected", testUnweightedFromUndirected),
        ("testUpdateEdge", testUpdateEdge),
        ("testWeightForEdge", testWeightForEdge),
    ]
}

extension Zip3SequenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Zip3SequenceTests = [
        ("testMany", testMany),
        ("testZip3Sequence", testZip3Sequence),
    ]
}

extension ZipToLongestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ZipToLongestTests = [
        ("testEqualLengths", testEqualLengths),
        ("testFirstLonger", testFirstLonger),
        ("testSecondLonger", testSecondLonger),
        ("testThirdLonger", testThirdLonger),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AVLTreeTests.__allTests__AVLTreeTests),
        testCase(AdjacencyListTests.__allTests__AdjacencyListTests),
        testCase(ArrayExtensionsTests.__allTests__ArrayExtensionsTests),
        testCase(BimapTests.__allTests__BimapTests),
        testCase(BinaryHeapTests.__allTests__BinaryHeapTests),
        testCase(BinarySearchTreeTests.__allTests__BinarySearchTreeTests),
        testCase(CircularArrayTests.__allTests__CircularArrayTests),
        testCase(ContiguousSegmentCollectionTests.__allTests__ContiguousSegmentCollectionTests),
        testCase(CrossTests.__allTests__CrossTests),
        testCase(DictionaryProtocolsTests.__allTests__DictionaryProtocolsTests),
        testCase(DirectedGraphTests.__allTests__DirectedGraphTests),
        testCase(EitherTests.__allTests__EitherTests),
        testCase(GraphTests.__allTests__GraphTests),
        testCase(HomogeneityTests.__allTests__HomogeneityTests),
        testCase(IntervalRelationTests.__allTests__IntervalRelationTests),
        testCase(InvertibleEnumTests.__allTests__InvertibleEnumTests),
        testCase(LinkedListTests.__allTests__LinkedListTests),
        testCase(MatrixTests.__allTests__MatrixTests),
        testCase(MetatypeTests.__allTests__MetatypeTests),
        testCase(MutableGraphTests.__allTests__MutableGraphTests),
        testCase(NewTypeTests.__allTests__NewTypeTests),
        testCase(OrderedDictionaryTests.__allTests__OrderedDictionaryTests),
        testCase(OrderedPairTests.__allTests__OrderedPairTests),
        testCase(PairsTests.__allTests__PairsTests),
        testCase(QueueTests.__allTests__QueueTests),
        testCase(ReferenceTreeProtocolTests.__allTests__ReferenceTreeProtocolTests),
        testCase(ReferenceTreeTests.__allTests__ReferenceTreeTests),
        testCase(SortedArrayTests.__allTests__SortedArrayTests),
        testCase(SortedDictionaryTests.__allTests__SortedDictionaryTests),
        testCase(StackTests.__allTests__StackTests),
        testCase(SubsetsTests.__allTests__SubsetsTests),
        testCase(TreeTests.__allTests__TreeTests),
        testCase(UnorderedPairTests.__allTests__UnorderedPairTests),
        testCase(WeightedDirectedGraphTests.__allTests__WeightedDirectedGraphTests),
        testCase(WeightedGraphTests.__allTests__WeightedGraphTests),
        testCase(Zip3SequenceTests.__allTests__Zip3SequenceTests),
        testCase(ZipToLongestTests.__allTests__ZipToLongestTests),
    ]
}
#endif
