#if !canImport(ObjectiveC)
import XCTest

extension GraphPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphPerformanceTests = [
        ("testEdgeFromSourceInCompleteGraph_O_n", testEdgeFromSourceInCompleteGraph_O_n),
        ("testEdgesFromSourceInGraph_O_n", testEdgesFromSourceInGraph_O_n),
        ("testEdgesFromSourceNotInGraph_O_1", testEdgesFromSourceNotInGraph_O_1),
        ("testEdgesToDestinationInGraph_O_n", testEdgesToDestinationInGraph_O_n),
        ("testEdgesToDestinationNotInGraph_O_1", testEdgesToDestinationNotInGraph_O_1),
        ("testInsertEdge_O_1", testInsertEdge_O_1),
        ("testInsertNode_O_1", testInsertNode_O_1),
        ("testNeighborsOfNodeInGraph_O_n", testNeighborsOfNodeInGraph_O_n),
        ("testNeighborsOfNodeNotInGraph_O_1", testNeighborsOfNodeNotInGraph_O_1),
        ("testProfile", testProfile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GraphPerformanceTests.__allTests__GraphPerformanceTests),
    ]
}
#endif
