#if !canImport(ObjectiveC)
import XCTest

extension BinaryHeapPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryHeapPerformanceTests = [
        ("testInsert_O_1", testInsert_O_1),
        ("testPop_O_1", testPop_O_1),
    ]
}

extension DirectedGraphPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DirectedGraphPerformanceTests = [
        ("testEdgesFromNode_O_1", testEdgesFromNode_O_1),
        ("testNeighborsOfNode_O_1", testNeighborsOfNode_O_1),
    ]
}

extension GraphPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphPerformanceTests = [
        ("testEdgeFromSourceInCompleteGraph_O_n", testEdgeFromSourceInCompleteGraph_O_n),
        ("testEdgesFromSourceInGraph_O_n", testEdgesFromSourceInGraph_O_n),
        ("testEdgesFromSourceNotInGraph_O_1", testEdgesFromSourceNotInGraph_O_1),
        ("testEdgesToDestinationInGraph_O_n", testEdgesToDestinationInGraph_O_n),
        ("testEdgesToDestinationNotInGraph_O_1", testEdgesToDestinationNotInGraph_O_1),
        ("testInsertEdge_O_1", testInsertEdge_O_1),
        ("testInsertNode_O_1", testInsertNode_O_1),
        ("testNeighborsOfNodeInGraph_O_n", testNeighborsOfNodeInGraph_O_n),
        ("testNeighborsOfNodeNotInGraph_O_1", testNeighborsOfNodeNotInGraph_O_1),
        ("testProfile", testProfile),
    ]
}

extension QueuePerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QueuePerformanceTests = [
        ("testDequeue_O_n", testDequeue_O_n),
        ("testEnqueue_O_1", testEnqueue_O_1),
        ("testIsEmpty_O_1", testIsEmpty_O_1),
        ("testPeek_O_1", testPeek_O_1),
    ]
}

extension WeightedDirectedGraphPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WeightedDirectedGraphPerformanceTests = [
        ("testEdgesFromNode_O_1", testEdgesFromNode_O_1),
        ("testNeighborsOfNode_O_1", testNeighborsOfNode_O_1),
    ]
}

extension WeightedGraphPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WeightedGraphPerformanceTests = [
        ("testNeighborsOfNode_O_1", testNeighborsOfNode_O_1),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BinaryHeapPerformanceTests.__allTests__BinaryHeapPerformanceTests),
        testCase(DirectedGraphPerformanceTests.__allTests__DirectedGraphPerformanceTests),
        testCase(GraphPerformanceTests.__allTests__GraphPerformanceTests),
        testCase(QueuePerformanceTests.__allTests__QueuePerformanceTests),
        testCase(WeightedDirectedGraphPerformanceTests.__allTests__WeightedDirectedGraphPerformanceTests),
        testCase(WeightedGraphPerformanceTests.__allTests__WeightedGraphPerformanceTests),
    ]
}
#endif
