#if !canImport(ObjectiveC)
import XCTest

extension CombinatoricsPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CombinatoricsPerformanceTests = [
        ("testCartesianProduct_O_n", testCartesianProduct_O_n),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CombinatoricsPerformanceTests.__allTests__CombinatoricsPerformanceTests),
    ]
}
#endif
